apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparta-app-deployment   # ← deployment/sparta-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparta-app
  template:
    metadata:
      labels:
        app: sparta-app
    spec:
      containers:
        - name: sparta-app      # ← sparta-app=
          image: nataliaveselova/sparta-app-k8s-gh
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"